"""
agents/pdf_agent.py
--------------------
Agent 5 — PDF Report Builder

Assembles the complete one-click PDF report using ReportLab.
The PDF contains:
  - Header with title and timestamp
  - User question and generated SQL
  - Embedded chart image (matplotlib PNG from state)
  - Anomaly detection results table
  - Executive summary (3 bullet points)
  - Footer with page number

Writes: pdf_path into state.
"""

from __future__ import annotations

import io
import logging
import os
from datetime import datetime

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle,
    HRFlowable,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER

from core.config import OUTPUT_DIR
from core.state import AgentState

logger = logging.getLogger(__name__)

PAGE_W, PAGE_H = A4
MARGIN = 2.0 * cm

# ── Style definitions ─────────────────────────────────────────────────────────

def _build_styles() -> dict:
    base   = getSampleStyleSheet()
    styles = {}

    styles["title"] = ParagraphStyle(
        "title",
        parent=base["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.black,
        spaceAfter=6,
        alignment=TA_CENTER,
    )
    styles["subtitle"] = ParagraphStyle(
        "subtitle",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=12,
        alignment=TA_CENTER,
    )
    styles["section"] = ParagraphStyle(
        "section",
        parent=base["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=colors.black,
        spaceBefore=14,
        spaceAfter=4,
    )
    styles["body"] = ParagraphStyle(
        "body",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.black,
        spaceAfter=4,
    )
    styles["code"] = ParagraphStyle(
        "code",
        parent=base["Code"],
        fontName="Courier",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#333333"),
        backColor=colors.HexColor("#F5F5F5"),
        borderPadding=(4, 6, 4, 6),
        spaceAfter=8,
    )
    styles["bullet"] = ParagraphStyle(
        "bullet",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=14,
        leftIndent=14,
        textColor=colors.black,
        spaceAfter=4,
    )
    return styles


# ── Data table helper ─────────────────────────────────────────────────────────

def _df_to_reportlab_table(df: pd.DataFrame, max_rows: int = 10) -> Table:
    """Convert a DataFrame to a ReportLab Table (header + up to max_rows rows)."""
    display_df = df.head(max_rows)

    # Header row
    header = [str(c) for c in display_df.columns]
    data   = [header]

    for _, row in display_df.iterrows():
        data.append([str(v) if v is not None else "" for v in row])

    col_count  = len(header)
    avail_w    = PAGE_W - 2 * MARGIN
    col_w      = avail_w / col_count

    tbl = Table(data, colWidths=[col_w] * col_count, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0),  colors.HexColor("#222222")),
        ("TEXTCOLOR",   (0, 0), (-1, 0),  colors.white),
        ("FONTNAME",    (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0),  8),
        ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 1), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F7F7")]),
        ("GRID",        (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("TOPPADDING",  (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ]))
    return tbl


# ── Page number footer ────────────────────────────────────────────────────────

def _footer_canvas(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.grey)
    canvas.drawRightString(
        PAGE_W - MARGIN,
        1.0 * cm,
        f"Page {doc.page}  |  Generated by BI Agent  |  {datetime.now().strftime('%d %b %Y %H:%M')}",
    )
    canvas.restoreState()


# ── LangGraph node ────────────────────────────────────────────────────────────

def pdf_agent(state: AgentState) -> AgentState:
    """LangGraph node: full state → PDF file written to OUTPUT_DIR"""
    timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename   = f"bi_report_{timestamp}.pdf"
    pdf_path   = os.path.join(OUTPUT_DIR, filename)
    styles     = _build_styles()

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=MARGIN,  rightMargin=MARGIN,
        topMargin=MARGIN,   bottomMargin=1.5 * cm,
    )

    story: list = []

    # ── 1. Title block ────────────────────────────────────────────────────────
    story.append(Paragraph("Business Intelligence Report", styles["title"]))
    story.append(Paragraph(
        datetime.now().strftime("Generated on %A, %d %B %Y at %H:%M"),
        styles["subtitle"],
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.black))
    story.append(Spacer(1, 0.3 * cm))

    # ── 2. Question ───────────────────────────────────────────────────────────
    story.append(Paragraph("User Question", styles["section"]))
    story.append(Paragraph(
        state.get("user_question", "N/A"),
        styles["body"],
    ))

    # ── 3. Generated SQL ──────────────────────────────────────────────────────
    story.append(Paragraph("SQL Query Executed", styles["section"]))
    sql_text = state.get("generated_sql", "N/A").replace("\n", "<br/>")
    story.append(Paragraph(sql_text, styles["code"]))

    # ── 4. Query result table ─────────────────────────────────────────────────
    df: pd.DataFrame | None = state.get("query_result")
    if df is not None and not df.empty:
        story.append(Paragraph(
            f"Query Results (showing up to 10 of {len(df)} rows)",
            styles["section"],
        ))
        story.append(_df_to_reportlab_table(df, max_rows=10))
        story.append(Spacer(1, 0.3 * cm))

    # ── 5. Chart ──────────────────────────────────────────────────────────────
    chart_png: bytes = state.get("chart_png", b"")
    if chart_png:
        story.append(Paragraph(
            f"Visualisation — {state.get('chart_title', '')}",
            styles["section"],
        ))
        story.append(Paragraph(
            f"Chart type: {state.get('chart_type', '')}. "
            f"{state.get('chart_rationale', '')}",
            styles["body"],
        ))
        img_buf = io.BytesIO(chart_png)
        avail_w = PAGE_W - 2 * MARGIN
        img = Image(img_buf, width=avail_w, height=avail_w * 0.45)
        story.append(img)
        story.append(Spacer(1, 0.3 * cm))

    # ── 6. Anomaly detection ──────────────────────────────────────────────────
    story.append(Paragraph("Anomaly Detection", styles["section"]))
    anomaly_method = state.get("anomaly_method", "none")
    story.append(Paragraph(
        f"Method used: {anomaly_method.replace('_', ' ').title()}",
        styles["body"],
    ))
    story.append(Paragraph(
        state.get("anomaly_explanation", "No anomaly analysis available."),
        styles["body"],
    ))

    anomaly_dates  = state.get("anomaly_dates",  [])
    anomaly_values = state.get("anomaly_values", [])
    if anomaly_dates and anomaly_method == "prophet":
        anom_data = [["Date", "Value"]] + [
            [str(d), f"{v:.4f}"]
            for d, v in zip(anomaly_dates[:10], anomaly_values[:10])
        ]
        anom_tbl = Table(anom_data, colWidths=[6 * cm, 5 * cm])
        anom_tbl.setStyle(TableStyle([
            ("BACKGROUND",  (0, 0), (-1, 0), colors.HexColor("#222222")),
            ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
            ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",    (0, 0), (-1, -1), 8),
            ("GRID",        (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
            ("TOPPADDING",  (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(Spacer(1, 0.2 * cm))
        story.append(anom_tbl)

    story.append(Spacer(1, 0.4 * cm))

    # ── 7. Executive summary ──────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph("Executive Summary", styles["section"]))

    summary = state.get("executive_summary", "No summary available.")
    for line in summary.splitlines():
        line = line.strip()
        if line:
            story.append(Paragraph(line, styles["bullet"]))

    # ── Build ─────────────────────────────────────────────────────────────────
    try:
        doc.build(story, onLaterPages=_footer_canvas, onFirstPage=_footer_canvas)
        logger.info("[pdf_agent] PDF written to: %s", pdf_path)
    except Exception as exc:
        logger.error("[pdf_agent] PDF generation failed: %s", exc)
        return {**state, "pdf_path": "", "error": f"PDF generation failed: {exc}"}

    return {**state, "pdf_path": pdf_path}
